Document: lsstack
Title: Debian lsstack Manual
Author: <insert document author here>
Abstract: This manual describes what lsstack is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lsstack/lsstack.sgml.gz

Format: postscript
Files: /usr/share/doc/lsstack/lsstack.ps.gz

Format: text
Files: /usr/share/doc/lsstack/lsstack.text.gz

Format: HTML
Index: /usr/share/doc/lsstack/html/index.html
Files: /usr/share/doc/lsstack/html/*.html
